### ISSUE TITLE
[이다솔] index.jsp 생성완료 - 확인해주세요

### ISSUE THREAD

**Issue by Leedasol2** [Leedasol2/SemiProject#109]
- 메인 / 헤더 담담님들 이미지 경로 설정하고 사용하시면 됩니다

- html 폴더에서 코드 긁어서 layout 폴더에 jsp 파일로 만드시면 됩니다

### 각자 작업 시작하시면 돼요. 다들 화이팅 🧡

**Comment by Leedasol2** [comment]
확인하시면 코멘트 하나씩 달아주세요~

**Comment by Wyna2** [comment]
확인했습니당🥕

**Comment by sjihwan** [comment]
확인했습니다~
