### ISSUE TITLE
[이다솔] 결제된 클래스 클릭시 유튜브 링크걸기

### ISSUE THREAD

**Issue by Leedasol2** [Leedasol2/SemiProject#193]
### 유튜브 링크걸기 

> 방안1. DB에서 lesson 테이블 update로 수정하여 링크도 같이 저장하기

- 너무 오래걸림. 모든 클래스 데이터 다시 넣어야함

> 방안2. 한 계정에만 링크 걸기

- 클릭시 이벤트로 직접적으로 유튜브 링크를 걸어놓기
- 가장 쉬운방법이지만 편법임..

> 방안 3. 링크 DB를 새로 만들어서 조인하여 링크 연결

- 몇몇 클래스에만 링크를 넣으면 됨 -> 시간 덜 잡아먹힘
- 사실상 지금 할 수 있는 최선의 방법

### 더 좋은 방안 있으신분들은 말씀해주세요!

**Comment by Wyna2** [comment]
방안1+3 섞어서 lesson 테이블 update로 url 컬럼 만들고 각 카테고리당 클래스 하나씩만 우선 링크 넣어놓는건 어떨까요?
백엔드 처리 빨리 끝나면 추가로 db 채워넣고요

**Comment by cdkfk96** [comment]
저도 나리님 의견 좋은것같아요!

**Comment by sjihwan** [comment]
저도 방안3이 가장 나을거 같고 나중에 시간 남으면 다같이 넣는거 어떨까요
